Starting methods for the VT library
voxeltycoon-community/voxel-tycoon-open-library pull request #1
Opened 2021-10-06 22:05 UTC by evertn

Added some methods concerning buildings

2021-10-06 22:09 UTC, kevin4998 approved these changes
Good work on your first Pull Request!

There is only one minor comment which you might want to look into.

2021-10-06 22:09 UTC, kevin4998 commented on Voxel Tycoon Open Library/VTOLBuilding.cs
> +        /// <summary>
[Suggestion]

Don't forget to add comments to the class as well.

2021-10-06 22:31 UTC, evertn commented on Voxel Tycoon Open Library/VTOLBuilding.cs
> +        /// <summary>
Suggested changes made

2021-10-08 19:51 UTC, kevin4998 approved these changes
All your code seems to work great on my end now as well, as discussed in voice chat.
However, since we both have been contributing to this branch now, it might be a good idea to let someone different from the two of us review it before merging.

2021-10-09 21:32 UTC, victorleblais requested changes
Just a few URLs that need to be updated, thanks for your work !

2021-10-09 21:32 UTC, victorleblais commented on README.md
> +</p>
Should be updated to the new repository URL: https://github.com/voxeltycoon-community/voxel-tycoon-open-library
Sorry !

2021-10-09 21:32 UTC, victorleblais commented on README.md
> +<h3 align="center"><a href="https://github.com/victorleblais/voxel-tycoon-open-library/blob/main/LICENSE"><b>GNU Affero General Public License v3.0</b></a></h3>
Same problem, URL needs to be voxeltycoon-community instead of victorleblais

2021-10-09 21:56 UTC, kevin4998 commented on README.md
> +</p>
Updated the URLs, and no need to apologise. Code is a dynamic thing, it will change over time. We just need to make it as easy of us to adjust it.

2021-10-09 21:59 UTC, victorleblais approved these changes

2021-10-09 21:59 UTC, merged