Create VTOLReflectionHelpers.cs
voxeltycoon-community/voxel-tycoon-open-library pull request #17
Opened 2021-11-23 18:02 UTC by evertn

- Added a new class VTOLReflectionHelpers
- Added a method to VTOLReflectionHelpers

2021-11-25 15:07 UTC, evertn commented
I found another issue when `object == null`. Should the method itself throw an error for this?

2021-11-25 15:46 UTC, kevin4998 requested changes
Thank you for adding the test library, it works well! And everything seems to be running as expected. I only found one minor bug when testing. Could you improve this then I will approve it?

2021-11-25 15:46 UTC, kevin4998 commented on tests/VTOL.Tests/VTOL.Tests.csproj
> +  </PropertyGroup>
[Recommended]

Thanks for adding the testing library for us! However, could you change the default namespace from `VTOL.Tests` to `VTOL`? The tests will function better if they are in the same namespace as the class which they are testing (since they can then access internal and protected fields).

2021-11-25 15:46 UTC, kevin4998 commented on tests/VTOL.Tests/VTOL.Tests.csproj
> +  </ItemGroup>
[Request]

All the different dependencies work well and the test succeed on my end as well! So it all works, however there does appear to be a newer version of all these packages. If you make any changes, could you update these to the latest version as well?

2021-11-25 15:46 UTC, kevin4998 commented on tests/VTOL.Tests/VTOLReflectionHelpersTests.cs
> +        }
[Suggestion]

Since the argument of `Assert.Catch<>(...)` is only a single line, how about converting the statement lambda (`() => { .. }`) into an expression lambda (`() => ...`)?

Also MS has a good document if you are interested in reading up more on [lambdas](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/lambda-expressions).

2021-11-25 15:46 UTC, kevin4998 commented on tests/VTOL.Tests/VTOLReflectionHelpersTests.cs
> +    {
[Suggestion]

The name of test methods are self explanatory enough to not really need any xml documentation but it might still be useful to give a simple description to test classes which describes which class they are testing and what the main purpose is of the class they want to test (what is the most important functionality?). Could you add a short description to this class?

2021-11-25 15:46 UTC, kevin4998 commented on tests/VTOL.Tests/VTOLReflectionHelpersTests.cs
> +    }
[Suggestion]

These classes are used in one of the tests but their purpose is not clear when you just look at the overall class itself. Could you add a bit of documentation here to explain what these classes do / are for? Also could you move these classes inside the `VTOLReflectionHelpersTests` class? That way the naming won't intervene with other test classes (as they are pretty generic).

2021-11-25 15:46 UTC, kevin4998 commented on Voxel Tycoon Open Library/VTOLReflectionHelpers.cs
> +        }
[Required]

The following code is to retrieve the setter from the parent class however, this can fail and throw an invalid exception in the case of:

```csharp
internal class ParentClass
{
    public int MyInteger { get; private set; }
}
internal class SubClass : ParentClass
{
    public new int MyInteger { get; }
}
```

Could you verify that `property.DeclaringType` and `DeclaringType.GetProperty(propertyName);` do not return null? And possibly add a Unit Test for these accordingly? (The documentation says that `property.DeclaringType` can return `null` but I have no idea in which scenario this would be the case, so you can leave this test out if you can't find it or write `property.DeclaringType?.GetProperty(...)`.)

2021-11-25 15:50 UTC, kevin4998 commented on Voxel Tycoon Open Library/VTOLReflectionHelpers.cs
> +        }
I saw your comment about the case of `object == null`, and yes, I do think this case should throw its own exception, possible `ArgumentNullException`.

2021-11-25 16:33 UTC, evertn commented on tests/VTOL.Tests/VTOL.Tests.csproj
> +  </PropertyGroup>
The namespace already is `VTOL`

2021-11-25 16:33 UTC, evertn commented on tests/VTOL.Tests/VTOL.Tests.csproj
> +  </ItemGroup>
Updated the packages

2021-11-25 16:41 UTC, evertn commented on tests/VTOL.Tests/VTOLReflectionHelpersTests.cs
> +        }
Agreed. Done

2021-11-25 16:47 UTC, evertn commented on tests/VTOL.Tests/VTOLReflectionHelpersTests.cs
> +    {
> a simple description to test classes which describes which class they are testing and what the main purpose is of the class they want to test (what is the most important functionality?)

Im assuming you mean what the purpose is of the class that is being tested? ie. `VTOLReflectionHelpers`.

2021-11-25 16:53 UTC, evertn commented on tests/VTOL.Tests/VTOLReflectionHelpersTests.cs
> +    }
Done and done

2021-11-25 17:02 UTC, evertn commented on Voxel Tycoon Open Library/VTOLReflectionHelpers.cs
> +        }
Concerning `property.DeclaringType` returning `null`: [Stack Overflow](https://stackoverflow.com/questions/35266010/can-propertyinfo-declaringtype-really-ever-be-null)

> It can be null if the property is defined in a module. In C# you cannot define such methods and properties without reflection (see PropertyBuilder). However, if you reference a VB.NET assembly, it can have such members.

According to this answer we dont have to worry about this situation.

2021-11-25 17:20 UTC, evertn commented on Voxel Tycoon Open Library/VTOLReflectionHelpers.cs
> +        }
> `internal class ParentClass
{
    public int MyInteger { get; private set; }
}
internal class SubClass : ParentClass
{
    public new int MyInteger { get; }
}`

Added a test for this situation

2021-11-26 17:09 UTC, kevin4998 commented on Voxel Tycoon Open Library/VTOLReflectionHelpers.cs
> +        }
(This discussion was cleared up in Discord)

2021-11-26 17:29 UTC, kevin4998 approved these changes

2021-11-26 17:40 UTC, merged