VTOLStorageManager addition
voxeltycoon-community/voxel-tycoon-open-library pull request #23
Opened 2021-12-24 02:45 UTC by evertn

Added classes, methods and patches required for allowing users to adjust connections between `StorageNetworkBuildings`.

2021-12-28 16:28 UTC, kevin4998 requested changes
It was not last weekend but hopefully I am still on time with the review.

As for the code, some important parts seemed to be missing, such as tests, documentation and design choices. The overall lines are good and the process is clear, let's hope this can become a popular system. If you have any questions you can always respond to these review points or contact me in Discord. Let's get this into VTOL!

2021-12-28 16:28 UTC, kevin4998 commented on Voxel Tycoon Open Library/support_classes/PotentialConnectionArgs.cs
> +            }
[Question]

Why is this `ArgumentException` thrown? And for what purpose? It is not clear to me why this is here, could you explain it? Same with the other `ArgumentException`.

2021-12-28 16:28 UTC, kevin4998 commented on Voxel Tycoon Open Library/method_patchers/FindSiblingsPatch.cs
> +        {
[Requirement]

Nice system but I do not see any tests. Would it be possible to add some tests to verify that this system actually works? You can do this by calling the `Postfix` method with a [mock object](https://github.com/moq/moq4). If you need more info about mocking then I can explain it to you outside of GitHub.

2021-12-28 17:07 UTC, kevin4998 commented on Voxel Tycoon Open Library/support_classes/PotentialConnectionArgs.cs
> +            }
If this is a condition which should always be present then you can make use of `Debug.Assert()` unlike the test assertions these are assumptions which you make in your code. These conditions should always be met or the application completely fails, you could use it here as follows:

```csharp
Debug.Assert(_connections.Count == _siblings.Count);
```

2022-01-06 16:38 UTC, evertn commented on Voxel Tycoon Open Library/VTOLStorageNetworkManager.cs
> +        }
The reason why I put this within the `class` is because this is the only `class` that will use it. Also I've been searching for a general opinion about this: [StackOverflow](https://stackoverflow.com/questions/7478195/where-to-locate-c-sharp-structs-how-to-organize-structs-within-a-project)

When putting it in a separate file, all classes will have access to it, Im not sure if that is right?

2022-01-06 17:36 UTC, evertn commented on Voxel Tycoon Open Library/VTOLStorageNetworkManager.cs
> +        }
Im not sure what you mean with _"their own DefaultDictionary"_?

2022-01-06 17:50 UTC, evertn commented on Voxel Tycoon Open Library/VTOLStorageNetworkManager.cs
> +        private readonly List<PriorityListener> _priorityListeners = new List<PriorityListener>();
Your suggestion of putting it in a `Dictionary<int, SortedList<Listener>>` would mean there is nothing to sort with. The reason why its put in a list with `PriorityListeners` first is because this struct also holds the priority the `Listener` was registered with. Once all the `Listener`'s have been put in the `Dictionary<int, IList<Listener>>`, the priority is lost.

2022-01-06 18:11 UTC, evertn commented on Voxel Tycoon Open Library/support_classes/PotentialConnectionArgs.cs
> +            }
Looking at the documentation on `Debug.Assert(_connections.Count == _siblings.Count);`, this is not throwing an error, just logging an error message?

2022-01-06 18:34 UTC, evertn commented on Voxel Tycoon Open Library/method_patchers/FindSiblingsPatch.cs
> +        {
I will write tests for this once the class itself is approved.

2022-01-06 18:37 UTC, evertn commented on Voxel Tycoon Open Library/VTOLStorageNetworkManager.cs
> +        }
After realizing we need to keep the `Priority` stored for logging purposes I will redesign this structure. 

We are required to store the priority with a reason, so mod makers can read the reasoning behind certain cancellations ánd at which priority this cancellation happens.

2022-01-06 18:43 UTC, evertn commented on Voxel Tycoon Open Library/VTOLStorageNetworkManager.cs
> +        }
Would it be possible to have VTOL create its own log-file?

2022-01-07 12:54 UTC, kevin4998 commented on Voxel Tycoon Open Library/VTOLStorageNetworkManager.cs
> +        }
```csharp
private void AddListener(int assetId, OnStorageNetworkUpdate listener)
{
    // Check if there is already a list for all listeners of this building.
    if (!_listeners.TryGetValue(assetId, out IList<OnStorageNetworkUpdate> listeners))
    {
        // If not, prepare a new list for all the listeners.
        listeners = _listeners[assetId] = new List<OnStorageNetworkUpdate>();
    }
    // Add the new listener to the collection.
    listeners.Add(listener);
}
```

2022-01-07 12:55 UTC, kevin4998 commented on Voxel Tycoon Open Library/VTOLStorageNetworkManager.cs
> +        private readonly List<PriorityListener> _priorityListeners = new List<PriorityListener>();
I mean it as in why not use `Dictionary<int, SortedList<PriorityListener>>`, why do you manually keep sorting it rather than use a sorted data structure?

2022-01-07 12:58 UTC, kevin4998 commented on Voxel Tycoon Open Library/support_classes/PotentialConnectionArgs.cs
> +            }
Are you using the System [`Debug.Assert()`](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.debug.assert?view=net-6.0) or the [`Trace.Assert()`](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.trace.assert?view=net-6.0) one rather than the Unity one?

2022-01-07 13:52 UTC, evertn commented on Voxel Tycoon Open Library/VTOLStorageNetworkManager.cs
> +        private readonly List<PriorityListener> _priorityListeners = new List<PriorityListener>();
If I would put the `PriorityListener` as a value in the `Dictionary`, it means that once something tries to retrieve a list of `Listeners` I have to create a list first, rather then being able to return a list with `Listeners` immediately.

2022-01-08 22:36 UTC, kevin4998 commented on Voxel Tycoon Open Library/VTOLStorageNetworkManager.cs
> +        private readonly List<PriorityListener> _priorityListeners = new List<PriorityListener>();
Should others be able to retrieve that list in the first place? I thought only we should see the full list and invoke it. If others can call that function at any moment then it can provide issues. So why not return the `PriorityListeners` instead if it is only us? And if you are concerned about calling them like a function then you can always create an `Invoke()` method in the `PriorityListener`?

2022-01-16 22:31 UTC, kevin4998 reviewed
I am impressed by how well you resolved all the comments. I saw some great naming changes happen in here such as the `ConnectionFilter` and `InvalidateSiblingsPatch`, the quality of the code is pretty high as well and very clear. Overall, I think you did a great job on this code and I am looking forward to seeing more become part of the VTOL project. Overall, great work!

2022-01-16 22:31 UTC, kevin4998 approved these changes

2022-01-17 00:54 UTC, merged